# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create on')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Update on')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('link', models.URLField(help_text='The URL to the image page', max_length=255, verbose_name='Photo link')),
                ('image_url', models.URLField(help_text='he URL to the image file itself', max_length=255, verbose_name='ImageURL')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'ordering': ['-timestamp', 'title'],
                'verbose_name_plural': 'Photos',
                'verbose_name': 'Photo',
            },
        ),
    ]
